In [27]:
import duckdb
import pandas as pd
import os
from datetime import datetime

In [28]:
con = duckdb.connect(database='dados_duckdb.db', read_only=False)

In [30]:
arquivo = 'z0019_1.csv'
data_ingestao = datetime.now()
df = pd.read_csv(f'../landing/{arquivo}', sep=';')
df['nome_arquivo'] = arquivo
df['data_ingestao'] = data_ingestao
df.head()

   NATBR     MAKTX WERKS  MAINS  LABST nome_arquivo              data_ingestao
0  10001  PARAFUSO  BT10    100    100  z0019_1.csv 2026-05-03 17:02:19.849034
1  10002   MARTELO  BT50    100   1500  z0019_1.csv 2026-05-03 17:02:19.849034
2  10003     PREGO  BT10    100     50  z0019_1.csv 2026-05-03 17:02:19.849034

In [31]:
con.execute("""
CREATE TABLE IF NOT EXISTS bronze_produtos (
            NATBR VARCHAR,
            MAKTX VARCHAR,
            WERKS VARCHAR,
            MAINS VARCHAR,
            LABST VARCHAR,
            nome_arquivo VARCHAR,
            data_ingestao TIMESTAMP
            )


""")

In [32]:
con.execute("INSERT INTO bronze_produtos SELECT * FROM df")

In [36]:
resultado = con.execute("SELECT * FROM bronze_z0019").fetchdf()
resultado.head(10)

   NATBR     MAKTX WERKS MAINS LABST nome_arquivo              data_ingestao
0  10001  PARAFUSO  BT10   100   100  z0019_1.csv 2026-05-03 16:12:07.706258
1  10002   MARTELO  BT50   100  1500  z0019_1.csv 2026-05-03 16:12:07.706258
2  10003     PREGO  BT10   100    50  z0019_1.csv 2026-05-03 16:12:07.706258
3  10004     SERRA  BT50   100   200  z0019_2.csv 2026-05-03 16:37:10.142303
4  10005   MACHADO  BT50   100   100  z0019_2.csv 2026-05-03 16:37:10.142303
5  10003     PREGO  BT10   100    60  z0019_2.csv 2026-05-03 16:37:10.142303
6  10001  PARAFUSO  BT10   100   100  z0019_1.csv 2026-05-03 17:02:19.849034
7  10002   MARTELO  BT50   100  1500  z0019_1.csv 2026-05-03 17:02:19.849034
8  10003     PREGO  BT10   100    50  z0019_1.csv 2026-05-03 17:02:19.849034

In [34]:
con.execute("ALTER TABLE bronze_produtos RENAME TO bronze_z0019")

In [37]:
con.close()